
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex. 
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,int len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 43
#define YY_END_OF_BUFFER 44
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[214] =
    {   0,
        0,    0,   44,   43,   42,   41,   28,   30,   43,   38,
       39,   36,   37,   37,   36,   29,   36,   36,   36,   36,
       36,   36,   36,   36,   36,   36,   36,   36,   31,   32,
       42,    0,   38,   34,   39,   36,   37,   37,   33,   37,
       36,   36,   36,   36,   36,   36,   36,   36,   36,   36,
       36,   36,   36,   36,   36,   36,   36,   36,    0,   37,
       36,   36,    8,   36,   36,   36,   36,   36,   36,   36,
       36,   36,   36,   36,   36,    5,   36,   36,   36,   40,
       37,   36,   36,   36,   36,   36,   36,   36,   36,   36,
       36,   36,   36,   11,   36,   36,   36,   36,   23,   36,

       36,   35,   36,   36,   36,   36,   36,   36,   36,   36,
       36,   24,   10,   36,   36,   36,   36,   36,   36,   36,
       36,   36,   36,   36,   36,   36,   36,   36,   36,   36,
       36,   36,   36,   36,   36,   36,   36,   36,    3,   36,
       36,   36,    9,   36,   36,   36,   36,   36,   36,    2,
        1,   36,   26,   36,   36,   36,    6,   36,   25,   36,
       36,   15,   36,   36,    4,   36,   12,   36,   36,   36,
       36,   36,   36,   36,   36,    7,   13,   36,   36,   36,
       36,   36,   36,   36,   36,   14,   36,   36,   36,   36,
       36,   36,   20,   19,   36,   36,   17,   18,   36,   36,

       36,   16,   21,   36,   36,   36,   36,   22,   36,   36,
       36,   27,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    1,    7,    1,    1,    1,    8,
        9,   10,   11,   11,   12,   13,   14,   15,   15,   15,
       15,   15,   15,   15,   15,   15,   15,   11,    1,    1,
       16,    1,    1,    1,   17,   18,   19,   19,   20,   19,
       19,   19,   21,   19,   19,   19,   22,   19,   19,   19,
       19,   23,   19,   24,   19,   25,   19,   19,   19,   19,
        1,    1,    1,    1,   19,    1,   26,   27,   28,   29,

       30,   31,   32,   33,   34,   35,   36,   37,   38,   39,
       40,   41,   42,   43,   44,   45,   46,   47,   48,   49,
       50,   19,   51,    1,   52,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[53] =
    {   0,
        1,    1,    1,    2,    1,    1,    1,    1,    1,    3,
        4,    5,    5,    5,    6,    4,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        1,    1
    } ;

static yyconst flex_int16_t yy_base[220] =
    {   0,
        0,    0,   81, 1682,   51, 1682, 1682, 1682,   66,   47,
        0,   46,   53,   55,   62,    0,   69,   80,   89,   96,
      111,  118,  125,  140,  147,  161,  168,  175, 1682, 1682,
       66,    0,   44, 1682,    0,  183,  191,   76, 1682,  198,
      206,  213,  221,  228,  236,  245,  252,  263,  285,  271,
      292,  299,  307,  314,  322,  330,  341,  348,   45,  355,
      364,  376,  383,  390,  397,  404,  412,  420,  428,  443,
      451,  460,  467,  474,  481,  495,  502,  513,  520, 1682,
      527,  534,  548,  555,  562,  570,  578,  586,  593,  600,
      621,  629,  636,  643,  657,  664,  671,  678,  692,  699,

      706,  612,  713,  728,  735,  742,  749,  756,  766,  773,
      780,  789,  803,  810,  817,  824,  831,  838,  845,  852,
      867,  874,  883,  890,  902,  909,  916,  923,  934,  942,
      951,  958,  965,  974,  981, 1000, 1008, 1015, 1024, 1033,
     1046, 1053, 1060, 1068, 1075, 1082, 1089, 1102, 1114, 1121,
     1128, 1135, 1143, 1150, 1157, 1164, 1171, 1185, 1192, 1199,
     1206, 1213, 1221, 1228, 1236, 1243, 1252, 1259, 1266, 1273,
     1280, 1289, 1296, 1304, 1320, 1327, 1336, 1343, 1350, 1357,
     1367, 1375, 1382, 1389, 1396, 1405, 1424, 1431, 1438, 1445,
     1461, 1468, 1475, 1483, 1491, 1498, 1505, 1512, 1520, 1529,

     1536, 1548, 1557, 1564, 1571, 1579, 1586, 1593, 1602, 1610,
     1618, 1627, 1682, 1655, 1658, 1662, 1666, 1670, 1675
    } ;

static yyconst flex_int16_t yy_def[220] =
    {   0,
      213,    1,  213,  213,  213,  213,  213,  213,  213,  214,
      215,  216,  217,  218,  216,  215,  216,  216,  216,  216,
      216,  216,  216,  216,  216,  216,  216,  216,  213,  213,
      213,  219,  214,  213,  215,  216,  217,  218,  213,  217,
      216,  216,  216,  216,  216,  216,  216,  216,  216,  216,
      216,  216,  216,  216,  216,  216,  216,  216,  219,  217,
      216,  216,  216,  216,  216,  216,  216,  216,  216,  216,
      216,  216,  216,  216,  216,  216,  216,  216,  216,  213,
      217,  216,  216,  216,  216,  216,  216,  216,  216,  216,
      216,  216,  216,  216,  216,  216,  216,  216,  216,  216,

      216,  217,  216,  216,  216,  216,  216,  216,  216,  216,
      216,  216,  216,  216,  216,  216,  216,  216,  216,  216,
      216,  216,  216,  216,  216,  216,  216,  216,  216,  216,
      216,  216,  216,  216,  216,  216,  216,  216,  216,  216,
      216,  216,  216,  216,  216,  216,  216,  216,  216,  216,
      216,  216,  216,  216,  216,  216,  216,  216,  216,  216,
      216,  216,  216,  216,  216,  216,  216,  216,  216,  216,
      216,  216,  216,  216,  216,  216,  216,  216,  216,  216,
      216,  216,  216,  216,  216,  216,  216,  216,  216,  216,
      216,  216,  216,  216,  216,  216,  216,  216,  216,  216,

      216,  216,  216,  216,  216,  216,  216,  216,  216,  216,
      216,  216,    0,  213,  213,  213,  213,  213,  213
    } ;

static yyconst flex_int16_t yy_nxt[1735] =
    {   0,
        4,    5,    6,    5,    7,    8,    9,    4,    4,   10,
       11,   12,   13,   14,   15,   16,   12,   12,   12,   12,
       12,   12,   12,   12,   17,   12,   12,   18,   19,   20,
       21,   12,   12,   12,   12,   12,   22,   12,   12,   12,
       23,   12,   24,   25,   26,   12,   27,   28,   12,   12,
       29,   30,   31,   80,   31,   33,   35,  213,   37,   38,
       34,   35,   33,   35,   39,   35,   38,   31,   35,   31,
       35,   33,   35,   32,   40,   38,   41,   35,   33,   35,
      213,   37,   38,  213,   35,  213,   35,  213,   42,   33,
       35,   35,   37,   38,  213,   35,  213,  213,   33,   35,

      213,   37,   38,  213,   35,   33,   35,  213,   37,   38,
      213,   35,  213,  213,  213,  213,   43,   44,   46,   45,
       33,   35,  213,   37,   38,  213,   35,   33,   35,  213,
       37,   38,  213,   35,   33,   35,   48,   37,   38,  213,
       35,  213,  213,  213,   47,  213,   50,   49,  213,   33,
       35,   51,   37,   38,  213,   35,   33,   35,  213,   37,
       38,  213,   35,  213,  213,  213,  213,   52,  213,   53,
       33,   35,  213,   37,   38,  213,   35,   33,   35,  213,
       37,   38,   54,   35,   33,   35,  213,   37,   38,   55,
       35,  213,   33,   35,  213,   37,   38,   57,   35,  213,

       33,   35,  213,   56,   38,  213,   35,   33,   35,  213,
      213,   38,   60,   35,   58,   33,   35,  213,   40,   38,
       41,   35,   33,   35,  213,   37,   38,  213,   35,  213,
       33,   35,  213,   37,   38,   61,   35,   33,   35,  213,
       37,   38,  213,   35,  213,   33,   35,  213,   37,   38,
       62,   35,  213,  213,   33,   35,   63,   37,   38,  213,
       35,   33,   35,  213,   37,   38,  213,   35,  213,  213,
      213,  213,   33,   35,   64,   37,   38,  213,   35,  213,
       33,   35,   71,   37,   38,   65,   35,  213,   66,  213,
      213,  213,   67,  213,   33,   35,   68,   37,   38,   69,

       35,   33,   35,  213,   37,   38,  213,   35,   33,   35,
       70,   37,   38,  213,   35,  213,   33,   35,   72,   37,
       38,  213,   35,   33,   35,  213,   37,   38,  213,   35,
      213,   33,   35,  213,   37,   38,  213,   35,   73,   33,
       35,  213,   37,   38,  213,   35,  213,   75,   74,   76,
       33,   35,  213,   37,   38,  213,   35,   33,   35,  213,
       37,   38,  213,   35,   33,   35,  213,   81,   38,   60,
       35,  213,  213,   33,   35,   77,   37,   38,  213,   35,
      213,   82,  213,   78,  213,   33,   35,  213,   37,   38,
       79,   35,   33,   35,  213,   37,   38,  213,   35,   33,

       35,   83,   37,   38,  213,   35,   33,   35,  213,   37,
       38,  213,   35,   33,   35,  213,   37,   38,  213,   35,
      213,   33,   35,  213,   37,   38,   85,   35,  213,   33,
       35,  213,   37,   38,  213,   35,   84,   33,   35,  213,
       37,   38,  213,   35,  213,  213,  213,  213,   86,   88,
      213,   87,   33,   35,  213,   37,   38,  213,   35,  213,
       33,   35,   89,   37,   38,  213,   35,  213,  213,   33,
       35,   90,   37,   38,   91,   35,   33,   35,  213,   37,
       38,   92,   35,   33,   35,  213,   37,   38,  213,   35,
       33,   35,  213,   37,   38,  213,   35,  213,   95,  213,

      213,  213,   93,   94,   33,   35,   98,   37,   38,  213,
       35,   33,   35,  213,   37,   38,  213,   35,  213,   96,
      213,   97,   33,   35,  213,   37,   38,  213,   35,   33,
       35,   99,   37,   38,  213,   35,   33,   35,  213,  213,
       38,  102,   35,   33,   35,  213,   37,   38,  213,   35,
      103,  213,  213,  213,  213,  101,  100,   33,   35,  213,
       37,   38,  213,   35,   33,   35,  213,   37,   38,  213,
       35,   33,   35,  213,   37,   38,  213,   35,  213,   33,
       35,  107,   37,   38,  105,   35,  104,   33,   35,  213,
       37,   38,  213,   35,  213,   33,   35,  213,   37,   38,

      106,   35,   33,   35,  213,   37,   38,  213,   35,   33,
       35,  213,   37,   38,  213,   35,  213,  213,  111,  213,
      108,   33,   35,  213,  109,   38,  102,   35,  110,  112,
       33,   35,  213,   37,   38,  213,   35,  213,   33,   35,
      213,   37,   38,  213,   35,   33,   35,  213,   37,   38,
      213,   35,   33,   35,  213,   37,   38,  213,   35,  213,
      213,  115,  213,  213,  113,  114,   33,   35,  213,   37,
       38,  213,   35,   33,   35,  213,   37,   38,  213,   35,
       33,   35,  118,   37,   38,  213,   35,   33,   35,  213,
       37,   38,  213,   35,  213,  213,  213,  117,  213,  116,

      213,   33,   35,  213,   37,   38,  119,   35,   33,   35,
      213,   37,   38,  213,   35,   33,   35,  213,   37,   38,
      213,   35,   33,   35,  213,   37,   38,  213,   35,  213,
      213,  213,  120,  213,  213,  121,  122,   33,   35,  123,
       37,   38,  213,   35,   33,   35,  213,   37,   38,  213,
       35,   33,   35,  213,   37,   38,  213,   35,   33,   35,
      213,   37,   38,  213,   35,   33,   35,  213,   37,   38,
      125,   35,  213,  124,  213,   33,   35,  126,   37,   38,
      213,   35,   33,   35,  213,   37,   38,  213,   35,   33,
       35,  130,   37,   38,  213,   35,  213,  213,   33,   35,

      127,   37,   38,  213,   35,  213,  213,  213,  213,  128,
      213,  129,   33,   35,  213,   37,   38,  213,   35,   33,
       35,  213,   37,   38,  213,   35,   33,   35,  213,   37,
       38,  213,   35,   33,   35,  131,   37,   38,  213,   35,
       33,   35,  213,   37,   38,  213,   35,   33,   35,  133,
       37,   38,  213,   35,   33,   35,  213,   37,   38,  132,
       35,   33,   35,  213,   37,   38,  213,   35,  213,  213,
      213,  135,  213,  134,  213,  213,   33,   35,  137,   37,
       38,  136,   35,   33,   35,  213,   37,   38,  213,   35,
      213,  138,   33,   35,  140,   37,   38,  213,   35,   33,

       35,  213,   37,   38,  213,   35,  213,  213,  213,  139,
      213,   33,   35,  141,   37,   38,  213,   35,   33,   35,
      213,   37,   38,  142,   35,   33,   35,  145,   37,   38,
      213,   35,   33,   35,  213,   37,   38,  213,   35,  213,
      213,  213,  144,   33,   35,  143,   37,   38,  213,   35,
      213,   33,   35,  213,   37,   38,  146,   35,  213,  147,
       33,   35,  213,   37,   38,  213,   35,   33,   35,  213,
       37,   38,  213,   35,   33,   35,  213,   37,   38,  213,
       35,  148,  149,   33,   35,  213,   37,   38,  213,   35,
       33,   35,  213,   37,   38,  213,   35,  213,  213,  213,

      213,  213,  151,  152,  213,  213,  213,  150,  213,   33,
       35,  153,   37,   38,  213,   35,  213,   33,   35,  154,
       37,   38,  213,   35,   33,   35,  213,   37,   38,  213,
       35,  213,  155,   33,   35,  213,   37,   38,  213,   35,
      213,  213,   33,   35,  156,   37,   38,  213,   35,  213,
      157,  213,  213,  158,  159,   33,   35,  213,   37,   38,
      213,   35,   33,   35,  213,   37,   38,  213,   35,   33,
       35,  213,   37,   38,  213,   35,  213,   33,   35,  160,
       37,   38,  161,   35,   33,   35,  213,   37,   38,  213,
       35,   33,   35,  213,   37,   38,  213,   35,   33,   35,

      213,   37,   38,  213,   35,  213,  213,  213,  163,  213,
      162,   33,   35,  213,   37,   38,  213,   35,  213,  213,
      213,  164,  213,   33,   35,  165,   37,   38,  166,   35,
       33,   35,  213,   37,   38,  213,   35,   33,   35,  213,
       37,   38,  213,   35,   33,   35,  168,   37,   38,  213,
       35,  213,   33,   35,  213,   37,   38,  167,   35,   33,
       35,  213,   37,   38,  213,   35,   33,   35,  213,   37,
       38,  213,   35,   33,   35,  213,   37,   38,  213,   35,
       33,   35,  170,   37,   38,  213,   35,  213,  213,  171,
      213,  213,  213,  169,   33,   35,  172,   37,   38,  213,

       35,   33,   35,  213,   37,   38,  213,   35,   33,   35,
      213,   37,   38,  213,   35,   33,   35,  213,   37,   38,
      213,   35,   33,   35,  213,   37,   38,  213,   35,  213,
       33,   35,  213,   37,   38,  173,   35,   33,   35,  213,
       37,   38,  213,   35,  174,   33,   35,  213,   37,   38,
      213,   35,   33,   35,  213,   37,   38,  213,   35,  175,
      213,   33,   35,  213,   37,   38,  176,   35,   33,   35,
      213,   37,   38,  213,   35,   33,   35,  177,   37,   38,
      213,   35,   33,   35,  213,   37,   38,  213,   35,   33,
       35,  213,   37,   38,  213,   35,  213,  178,   33,   35,

      213,   37,   38,  213,   35,   33,   35,  213,   37,   38,
      179,   35,  213,   33,   35,  180,   37,   38,  213,   35,
      213,  213,  182,  213,  181,  184,  213,  183,  213,   33,
       35,  185,   37,   38,  213,   35,   33,   35,  213,   37,
       38,  213,   35,  213,  213,   33,   35,  186,   37,   38,
      213,   35,   33,   35,  213,   37,   38,  213,   35,   33,
       35,  213,   37,   38,  213,   35,   33,   35,  213,   37,
       38,  213,   35,  213,  187,  188,   33,   35,  213,   37,
       38,  213,   35,  213,   33,   35,  189,   37,   38,  213,
       35,   33,   35,  213,   37,   38,  213,   35,   33,   35,

      190,   37,   38,  213,   35,   33,   35,  213,   37,   38,
      213,   35,  213,  191,   33,   35,  213,   37,   38,  213,
       35,  213,  213,  213,  213,  194,  213,  192,  213,  213,
      213,  213,  193,   33,   35,  195,   37,   38,  213,   35,
       33,   35,  213,   37,   38,  213,   35,   33,   35,  213,
       37,   38,  213,   35,   33,   35,  213,   37,   38,  213,
       35,  213,  213,  213,  213,  213,  197,  196,  213,  213,
       33,   35,  198,   37,   38,  213,   35,   33,   35,  213,
       37,   38,  213,   35,   33,   35,  213,   37,   38,  213,
       35,  199,   33,   35,  213,   37,   38,  213,   35,  213,

       33,   35,  213,   37,   38,  200,   35,   33,   35,  213,
       37,   38,  213,   35,   33,   35,  213,   37,   38,  213,
       35,   33,   35,  213,   37,   38,  213,   35,  213,   33,
       35,  213,   37,   38,  202,   35,  213,  201,   33,   35,
      213,   37,   38,  213,   35,   33,   35,  213,   37,   38,
      213,   35,  213,  213,  213,  204,  213,   33,   35,  203,
       37,   38,  213,   35,  213,  205,   33,   35,  213,   37,
       38,  213,   35,   33,   35,  213,   37,   38,  213,   35,
       33,   35,  213,   37,   38,  213,   35,  213,   33,   35,
      213,   37,   38,  206,   35,   33,   35,  213,   37,   38,

      213,   35,   33,   35,  213,   37,   38,  213,   35,  213,
      213,   33,   35,  207,   37,   38,  213,   35,  213,   33,
       35,  208,   37,   38,  213,   35,  213,   33,   35,  209,
       37,   38,  213,   35,  213,  210,   33,   35,  213,   37,
       38,  213,   35,  213,  213,  213,  213,  213,  213,  211,
      213,  213,  213,  213,  213,  213,  212,   33,  213,   33,
       33,   35,   35,   35,   36,   36,   36,   36,   37,   37,
       37,   37,   38,   38,   38,   38,   59,  213,  213,  213,
       59,    3,  213,  213,  213,  213,  213,  213,  213,  213,
      213,  213,  213,  213,  213,  213,  213,  213,  213,  213,

      213,  213,  213,  213,  213,  213,  213,  213,  213,  213,
      213,  213,  213,  213,  213,  213,  213,  213,  213,  213,
      213,  213,  213,  213,  213,  213,  213,  213,  213,  213,
      213,  213,  213,  213
    } ;

static yyconst flex_int16_t yy_chk[1735] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    5,   59,    5,   12,   12,   33,   12,   12,
       10,   12,   13,   13,   14,   14,   13,   31,   13,   31,
       14,   15,   15,    9,   15,   15,   15,   15,   17,   17,
        3,   17,   17,    0,   17,   38,   38,    0,   17,   18,
       18,   38,   18,   18,    0,   18,    0,    0,   19,   19,

        0,   19,   19,    0,   19,   20,   20,    0,   20,   20,
        0,   20,    0,    0,    0,    0,   18,   18,   19,   18,
       21,   21,    0,   21,   21,    0,   21,   22,   22,    0,
       22,   22,    0,   22,   23,   23,   21,   23,   23,    0,
       23,    0,    0,    0,   20,    0,   22,   21,    0,   24,
       24,   22,   24,   24,    0,   24,   25,   25,    0,   25,
       25,    0,   25,    0,    0,    0,    0,   23,    0,   24,
       26,   26,    0,   26,   26,    0,   26,   27,   27,    0,
       27,   27,   25,   27,   28,   28,    0,   28,   28,   25,
       28,    0,   36,   36,    0,   36,   36,   27,   36,    0,

       37,   37,    0,   26,   37,    0,   37,   40,   40,    0,
        0,   40,   40,   40,   28,   41,   41,    0,   41,   41,
       41,   41,   42,   42,    0,   42,   42,    0,   42,    0,
       43,   43,    0,   43,   43,   42,   43,   44,   44,    0,
       44,   44,    0,   44,    0,   45,   45,    0,   45,   45,
       43,   45,    0,    0,   46,   46,   44,   46,   46,    0,
       46,   47,   47,    0,   47,   47,    0,   47,    0,    0,
        0,    0,   48,   48,   45,   48,   48,    0,   48,    0,
       50,   50,   50,   50,   50,   46,   50,    0,   46,    0,
        0,    0,   47,    0,   49,   49,   47,   49,   49,   48,

       49,   51,   51,    0,   51,   51,    0,   51,   52,   52,
       49,   52,   52,    0,   52,    0,   53,   53,   51,   53,
       53,    0,   53,   54,   54,    0,   54,   54,    0,   54,
        0,   55,   55,    0,   55,   55,    0,   55,   52,   56,
       56,    0,   56,   56,    0,   56,    0,   54,   53,   55,
       57,   57,    0,   57,   57,    0,   57,   58,   58,    0,
       58,   58,    0,   58,   60,   60,    0,   60,   60,   60,
       60,    0,    0,   61,   61,   56,   61,   61,    0,   61,
        0,   61,    0,   57,    0,   62,   62,    0,   62,   62,
       58,   62,   63,   63,    0,   63,   63,    0,   63,   64,

       64,   62,   64,   64,    0,   64,   65,   65,    0,   65,
       65,    0,   65,   66,   66,    0,   66,   66,    0,   66,
        0,   67,   67,    0,   67,   67,   65,   67,    0,   68,
       68,    0,   68,   68,    0,   68,   64,   69,   69,    0,
       69,   69,    0,   69,    0,    0,    0,    0,   66,   68,
        0,   67,   70,   70,    0,   70,   70,    0,   70,    0,
       71,   71,   68,   71,   71,    0,   71,    0,    0,   72,
       72,   69,   72,   72,   70,   72,   73,   73,    0,   73,
       73,   71,   73,   74,   74,    0,   74,   74,    0,   74,
       75,   75,    0,   75,   75,    0,   75,    0,   73,    0,

        0,    0,   72,   72,   76,   76,   76,   76,   76,    0,
       76,   77,   77,    0,   77,   77,    0,   77,    0,   74,
        0,   75,   78,   78,    0,   78,   78,    0,   78,   79,
       79,   77,   79,   79,    0,   79,   81,   81,    0,    0,
       81,   81,   81,   82,   82,    0,   82,   82,    0,   82,
       82,    0,    0,    0,    0,   79,   78,   83,   83,    0,
       83,   83,    0,   83,   84,   84,    0,   84,   84,    0,
       84,   85,   85,    0,   85,   85,    0,   85,    0,   86,
       86,   86,   86,   86,   84,   86,   83,   87,   87,    0,
       87,   87,    0,   87,    0,   88,   88,    0,   88,   88,

       85,   88,   89,   89,    0,   89,   89,    0,   89,   90,
       90,    0,   90,   90,    0,   90,    0,    0,   89,    0,
       87,  102,  102,    0,   88,  102,  102,  102,   88,   90,
       91,   91,    0,   91,   91,    0,   91,    0,   92,   92,
        0,   92,   92,    0,   92,   93,   93,    0,   93,   93,
        0,   93,   94,   94,    0,   94,   94,    0,   94,    0,
        0,   93,    0,    0,   91,   92,   95,   95,    0,   95,
       95,    0,   95,   96,   96,    0,   96,   96,    0,   96,
       97,   97,   97,   97,   97,    0,   97,   98,   98,    0,
       98,   98,    0,   98,    0,    0,    0,   96,    0,   95,

        0,   99,   99,    0,   99,   99,   98,   99,  100,  100,
        0,  100,  100,    0,  100,  101,  101,    0,  101,  101,
        0,  101,  103,  103,    0,  103,  103,    0,  103,    0,
        0,    0,  100,    0,    0,  101,  103,  104,  104,  104,
      104,  104,    0,  104,  105,  105,    0,  105,  105,    0,
      105,  106,  106,    0,  106,  106,    0,  106,  107,  107,
        0,  107,  107,    0,  107,  108,  108,    0,  108,  108,
      106,  108,    0,  105,    0,  109,  109,  107,  109,  109,
        0,  109,  110,  110,    0,  110,  110,    0,  110,  111,
      111,  111,  111,  111,    0,  111,    0,    0,  112,  112,

      108,  112,  112,    0,  112,    0,    0,    0,    0,  109,
        0,  110,  113,  113,    0,  113,  113,    0,  113,  114,
      114,    0,  114,  114,    0,  114,  115,  115,    0,  115,
      115,    0,  115,  116,  116,  114,  116,  116,    0,  116,
      117,  117,    0,  117,  117,    0,  117,  118,  118,  116,
      118,  118,    0,  118,  119,  119,    0,  119,  119,  115,
      119,  120,  120,    0,  120,  120,    0,  120,    0,    0,
        0,  118,    0,  117,    0,    0,  121,  121,  119,  121,
      121,  118,  121,  122,  122,    0,  122,  122,    0,  122,
        0,  120,  123,  123,  122,  123,  123,    0,  123,  124,

      124,    0,  124,  124,    0,  124,    0,    0,    0,  121,
        0,  125,  125,  123,  125,  125,    0,  125,  126,  126,
        0,  126,  126,  124,  126,  127,  127,  127,  127,  127,
        0,  127,  128,  128,    0,  128,  128,    0,  128,    0,
        0,    0,  126,  129,  129,  125,  129,  129,    0,  129,
        0,  130,  130,    0,  130,  130,  128,  130,    0,  129,
      131,  131,    0,  131,  131,    0,  131,  132,  132,    0,
      132,  132,    0,  132,  133,  133,    0,  133,  133,    0,
      133,  130,  131,  134,  134,    0,  134,  134,    0,  134,
      135,  135,    0,  135,  135,    0,  135,    0,    0,    0,

        0,    0,  133,  134,    0,    0,    0,  132,    0,  136,
      136,  135,  136,  136,    0,  136,    0,  137,  137,  135,
      137,  137,    0,  137,  138,  138,    0,  138,  138,    0,
      138,    0,  136,  139,  139,    0,  139,  139,    0,  139,
        0,    0,  140,  140,  136,  140,  140,    0,  140,    0,
      137,    0,    0,  138,  140,  141,  141,    0,  141,  141,
        0,  141,  142,  142,    0,  142,  142,    0,  142,  143,
      143,    0,  143,  143,    0,  143,    0,  144,  144,  141,
      144,  144,  142,  144,  145,  145,    0,  145,  145,    0,
      145,  146,  146,    0,  146,  146,    0,  146,  147,  147,

        0,  147,  147,    0,  147,    0,    0,    0,  145,    0,
      144,  148,  148,    0,  148,  148,    0,  148,    0,    0,
        0,  146,    0,  149,  149,  147,  149,  149,  148,  149,
      150,  150,    0,  150,  150,    0,  150,  151,  151,    0,
      151,  151,    0,  151,  152,  152,  152,  152,  152,    0,
      152,    0,  153,  153,    0,  153,  153,  149,  153,  154,
      154,    0,  154,  154,    0,  154,  155,  155,    0,  155,
      155,    0,  155,  156,  156,    0,  156,  156,    0,  156,
      157,  157,  155,  157,  157,    0,  157,    0,    0,  156,
        0,    0,    0,  154,  158,  158,  158,  158,  158,    0,

      158,  159,  159,    0,  159,  159,    0,  159,  160,  160,
        0,  160,  160,    0,  160,  161,  161,    0,  161,  161,
        0,  161,  162,  162,    0,  162,  162,    0,  162,    0,
      163,  163,    0,  163,  163,  160,  163,  164,  164,    0,
      164,  164,    0,  164,  161,  165,  165,    0,  165,  165,
        0,  165,  166,  166,    0,  166,  166,    0,  166,  163,
        0,  167,  167,    0,  167,  167,  164,  167,  168,  168,
        0,  168,  168,    0,  168,  169,  169,  166,  169,  169,
        0,  169,  170,  170,    0,  170,  170,    0,  170,  171,
      171,    0,  171,  171,    0,  171,    0,  168,  172,  172,

        0,  172,  172,    0,  172,  173,  173,    0,  173,  173,
      169,  173,    0,  174,  174,  170,  174,  174,    0,  174,
        0,    0,  172,    0,  171,  173,    0,  172,    0,  175,
      175,  174,  175,  175,    0,  175,  176,  176,    0,  176,
      176,    0,  176,    0,    0,  177,  177,  175,  177,  177,
        0,  177,  178,  178,    0,  178,  178,    0,  178,  179,
      179,    0,  179,  179,    0,  179,  180,  180,    0,  180,
      180,    0,  180,    0,  178,  179,  181,  181,    0,  181,
      181,    0,  181,    0,  182,  182,  180,  182,  182,    0,
      182,  183,  183,    0,  183,  183,    0,  183,  184,  184,

      181,  184,  184,    0,  184,  185,  185,    0,  185,  185,
        0,  185,    0,  182,  186,  186,    0,  186,  186,    0,
      186,    0,    0,    0,    0,  185,    0,  183,    0,    0,
        0,    0,  184,  187,  187,  187,  187,  187,    0,  187,
      188,  188,    0,  188,  188,    0,  188,  189,  189,    0,
      189,  189,    0,  189,  190,  190,    0,  190,  190,    0,
      190,    0,    0,    0,    0,    0,  189,  188,    0,    0,
      191,  191,  190,  191,  191,    0,  191,  192,  192,    0,
      192,  192,    0,  192,  193,  193,    0,  193,  193,    0,
      193,  191,  194,  194,    0,  194,  194,    0,  194,    0,

      195,  195,    0,  195,  195,  192,  195,  196,  196,    0,
      196,  196,    0,  196,  197,  197,    0,  197,  197,    0,
      197,  198,  198,    0,  198,  198,    0,  198,    0,  199,
      199,    0,  199,  199,  196,  199,    0,  195,  200,  200,
        0,  200,  200,    0,  200,  201,  201,    0,  201,  201,
        0,  201,    0,    0,    0,  200,    0,  202,  202,  199,
      202,  202,    0,  202,    0,  201,  203,  203,    0,  203,
      203,    0,  203,  204,  204,    0,  204,  204,    0,  204,
      205,  205,    0,  205,  205,    0,  205,    0,  206,  206,
        0,  206,  206,  204,  206,  207,  207,    0,  207,  207,

        0,  207,  208,  208,    0,  208,  208,    0,  208,    0,
        0,  209,  209,  205,  209,  209,    0,  209,    0,  210,
      210,  206,  210,  210,    0,  210,    0,  211,  211,  207,
      211,  211,    0,  211,    0,  209,  212,  212,    0,  212,
      212,    0,  212,    0,    0,    0,    0,    0,    0,  210,
        0,    0,    0,    0,    0,    0,  211,  214,    0,  214,
      214,  215,  215,  215,  216,  216,  216,  216,  217,  217,
      217,  217,  218,  218,  218,  218,  219,    0,    0,    0,
      219,  213,  213,  213,  213,  213,  213,  213,  213,  213,
      213,  213,  213,  213,  213,  213,  213,  213,  213,  213,

      213,  213,  213,  213,  213,  213,  213,  213,  213,  213,
      213,  213,  213,  213,  213,  213,  213,  213,  213,  213,
      213,  213,  213,  213,  213,  213,  213,  213,  213,  213,
      213,  213,  213,  213
    } ;

/* Table of booleans, true if rule could match eol. */
static yyconst flex_int32_t yy_rule_can_match_eol[44] =
    {   0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 1, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "rules.l"
#line 2 "rules.l"
#include <stdio.h>

#define YYSTYPE char*
#include "y.tab.h"

extern int yyget_lineno();
extern void set_parsererror(int, int, char*);

static void lexer_error()
{
   set_parsererror(0, yyget_lineno(), yytext);
}

int found_verbatim = 0;

static void abort_parsing_now()
{
   found_verbatim = 1;
}

#define ECHO lexer_error()

#define YY_NO_INPUT 1
#line 956 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

int yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 30 "rules.l"

#line 1143 "lex.yy.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 214 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1682 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					   
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 31 "rules.l"
return PROGRAM; 
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 32 "rules.l"
return LIBRARY;
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 33 "rules.l"
return WORKER;
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 34 "rules.l"
return CONF_MAKE_INSTALL;
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 35 "rules.l"
return SRC;
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 36 "rules.l"
return SRC_DIR;
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 37 "rules.l"
return SRC_EXTENSION;
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 38 "rules.l"
return COMMAND;
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 39 "rules.l"
return DEPENDS; 
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 40 "rules.l"
return FLAGS;
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 41 "rules.l"
return LIBS;
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 42 "rules.l"
return LDFLAGS;
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 43 "rules.l"
return ADD_OBJECTS;
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 44 "rules.l"
return EXPORT_INC;
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 45 "rules.l"
return DESTDIR;
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 46 "rules.l"
return SKIP_INSTALL;
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 47 "rules.l"
return SKIP_SHARED;
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 48 "rules.l"
return SKIP_STATIC;
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 49 "rules.l"
return CONVENIENCE_LIB;
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 50 "rules.l"
return CLEAN_FILES;
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 51 "rules.l"
return VERSION_INFO;
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 52 "rules.l"
return VERSION_NUMBER;
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 53 "rules.l"
return TRUE_VALUE;
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 54 "rules.l"
return FALSE_VALUE;
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 55 "rules.l"
abort_parsing_now(); return EOF; 
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 56 "rules.l"
return SKIP_IF;
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 57 "rules.l"
return REQUIRE_NAMGEN_VERSION;
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 59 "rules.l"
return EXPR_MARK;
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 60 "rules.l"
return EQUALS;
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 61 "rules.l"
return QUOTE;
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 62 "rules.l"
return OBRACE;
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 63 "rules.l"
return EBRACE;
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 64 "rules.l"
return OCOMMENT;
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 65 "rules.l"
return ECOMMENT;
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 67 "rules.l"
yylval = strdup(yytext); return THREE_NUMBERS;
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 68 "rules.l"
yylval = strdup(yytext); return WORD;
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 69 "rules.l"
yylval = strdup(yytext); return FILENAME;
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 70 "rules.l"
yylval = strdup(yytext); return WILDCARD;
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 71 "rules.l"
yylval = strdup(yytext); return STUFF;
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 72 "rules.l"
yylval = strdup(yytext); return VARIABLE;
	YY_BREAK
case 41:
/* rule 41 can match eol */
YY_RULE_SETUP
#line 74 "rules.l"
/* igore newlines */; 
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 75 "rules.l"
/* ignore whitespace */;
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 76 "rules.l"
ECHO;
	YY_BREAK
#line 1452 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 214 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 214 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 213);

	return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		   
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 76 "rules.l"



